DELETE http://localhost:3003/api/blogs/61af25c342de290c31203130
Content-Type: application/json


// NOTE: This does not work if item with above ID does not exist.
// Used this to prove delete method works.